grafana:
  enabled: true
  adminPassword: "ChangeMe123!"
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.local
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - grafana.local
        secretName: grafana-tls

prometheus:
  prometheusSpec:
    retention: 15d
    scrapeInterval: 15s
    evaluationInterval: 15s
    enableAdminAPI: false
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
